name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  blackboxtests:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Check simplest 
        run: | 
          wget https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          mkdir -p ./tmp/bin && mv appimagetool-x86_64.AppImage ./tmp/bin
          export PATH=`pwd`/tmp/bin:$PATH
          ./docker2appimage -i hello-world
